[package]
name = "gaen"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
anyhow = "1.0.100"
pollster = "0.4.0"
env_logger = "0.11.8"
log = "0.4.28"
wgpu = "27.0.1"
bytemuck = { version = "1.24.0", features = ["derive"] }
glam = "0.30.8"
hecs = "0.10.5"
